apiVersion: v1
kind: Namespace
metadata:
  name: mergen
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mergen-core
  namespace: mergen
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mergen-agent
  namespace: mergen
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mergen-core-jobs
  namespace: mergen
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mergen-core-jobs
  namespace: mergen
subjects:
  - kind: ServiceAccount
    name: mergen-core
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mergen-core-jobs
